// GUI/PAGES

use embassy_futures::select::{select, Either};
use embassy_time::{Duration, Instant, Timer};

use crate::components::gt911::{Gesture, SwipeDirection, TouchPoint};
use crate::*;

// CONSTANTS
const TAP_MAX_MOVEMENT:      u16 = 20;
const SWIPE_MIN_DISTANCE:    u16 = 40;
const DOUBLE_TAP_MAX_DIST:   u16 = 50;
const DOUBLE_TAP_TIMEOUT:    Duration = Duration::from_millis(400);


const DISPLAY_WIDTH:  u16 = 320;
const DISPLAY_HEIGHT: u16 = 240;


const BOTTOM_SWIPE_THRESHOLD: u16 = 40;
const TOP_SWIPE_THRESHOLD:    u16 = 40;


const TRACKING_POLL_INTERVAL: Duration = Duration::from_millis(10);

pub static TOUCH_EVENTS: embassy_sync::signal::Signal<
    embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex,
    TouchEvent,
> = embassy_sync::signal::Signal::new();

#[derive(Clone, Copy, defmt::Format)]
pub enum TouchEvent {
    Tap { x: u16, y: u16 },
    DoubleTap { x: u16, y: u16 },
    Swipe(SwipeDirection, u16, u16),
}



// ───────────────────────────────────────────────────────────────────────
// PAGE DEFINITIONS – macro 
crate::define_pages! {
    // MAIN PAGES
    Apps        = 0,  is_settings: false, prev: None, next: None;
    Clock       = 1,  is_settings: false, prev: None, next: None;
    Battery     = 2,  is_settings: false, prev: None, next: None;
    Weather     = 3,  is_settings: false, prev: None, next: None;

    // APPS
    DuckTv      = 11, is_settings: false, prev: None, next: None;
    Settings    = 14, is_settings: true,  prev: None, next: SettingsWifi;
    Zigduck     = 15, is_settings: false, prev: None, next: None;    

    // SPECIAL PAGES
    Call      = 100, is_settings: false, prev: None, next: None;

    // SETTINGS SUBPAGES
    SettingsWifi    = 140, is_settings: true, prev: SettingsInfo,    next: SettingsRssi,    tap: wifi;
    SettingsRssi    = 141, is_settings: true, prev: SettingsWifi,    next: SettingsBle,     tap: rssi;
    SettingsBle     = 142, is_settings: true, prev: SettingsRssi,    next: SettingsApi,     tap: bluetooth;
    SettingsApi     = 143, is_settings: true, prev: SettingsBle,     next: SettingsWake,    tap: api;
    SettingsWake    = 144, is_settings: true, prev: SettingsApi,     next: SettingsStream,  tap: wakeword;
    SettingsStream  = 145, is_settings: true, prev: SettingsWake,    next: SettingsSpeaker, tap: streaming;
    SettingsSpeaker = 146, is_settings: true, prev: SettingsStream,  next: SettingsMic,     swipe: speaker, tap: speaker;
    SettingsMic     = 147, is_settings: true, prev: SettingsSpeaker, next: SettingsDisplay, swipe: mic,      tap: mic;
    SettingsDisplay = 148, is_settings: true, prev: SettingsMic,     next: SettingsAmp,     swipe: display,  tap: display;
    SettingsAmp     = 150, is_settings: true, prev: SettingsDisplay, next: SettingsCpu,    tap: amplifier;
    SettingsCpu     = 151, is_settings: true, prev: SettingsAmp,     next: SettingsSleep,  swipe: cpu;
    SettingsSleep   = 152, is_settings: true, prev: SettingsCpu,     next: SettingsVpn,    swipe: sleep;
    SettingsVpn     = 154, is_settings: true, prev: SettingsSleep,   next: SettingsInfo,   tap: vpn;    
    SettingsInfo    = 155, is_settings: true, prev: SettingsVpn,     next: SettingsWifi,   swipe: info;

}


// MAIN NAVIGATION (NOT GENERATED BY THE MACRO)
impl Page {
    pub fn next_main(&self) -> Self {
        match self {
            Page::Apps    => Page::Clock,
            Page::Clock   => Page::Battery,
            Page::Battery => Page::Weather,
            Page::Weather => Page::Weather, // STOP – NO FURTHER
            _             => Page::Clock,
        }
    }

    pub fn prev_main(&self) -> Self {
        match self {
            Page::Clock      => Page::Apps,
            Page::Battery   => Page::Clock,
            Page::Weather => Page::Battery,
            Page::Apps       => Page::Apps, // STOP – NO FURTHER
            _                        => Page::Clock,
        }
    }
    
    // MAIN APPLICATIONS (CLOSED BY SWIPING UP FROM BOTTOM OF DISPLAY)
    pub fn is_app_page(&self) -> bool {
        self.is_settings_page()
            || matches!(self, Page::DuckTv)
    }

    // FETCHES PAGE NUMBER AS RAW u8
    pub fn as_raw(self) -> u8 { self as u8 }
}

// ───────────────────────────────────────────────────────────────────────
// INTERNAL HELPERS FOR THIS MODULE
crate::init_u8!(CURRENT_PAGE, 1);

pub fn current_page() -> Page {
    let raw = crate::load!(CURRENT_PAGE);
    Page::from_raw(raw).unwrap_or(Page::Clock)
}

pub fn set_page(page: Page) {
    crate::store!(CURRENT_PAGE, page.as_raw());
}


use esp_hal::i2c::master::I2c;



use crate::components::gt911::Gt911Blocking;

// ───────────────────────────────────────────────────────────────────────
// TOUCH TASK (TODO) 
#[embassy_executor::task]
pub async fn touch_task() {
    let touch = Gt911Blocking::default();

    loop {
        let result = critical_section::with(|cs| {
            let mut bus = crate::I2C_BUS.borrow_ref_mut(cs);
            let i2c = bus.as_mut().expect("I2C bus not available");
            touch.get_touch(i2c)
        });

        if let Ok(Some(point)) = result {
            defmt::info!("Touch: {}", defmt::Debug2Format(&point));

            TOUCH_EVENTS.signal(TouchEvent::Tap { x: point.x, y: point.y });
        }

        Timer::after(TRACKING_POLL_INTERVAL).await;
    }
}
